services:
    _defaults:
        public: true

    App\Infrastructure\Service\ParamConverter\PostParamConverter:
        arguments:
            - '@App\Infrastructure\Repository\PostRepository'
        tags:
            - { name: request.param_converter, converter: post }
