nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['Access-Control-Allow-Origin', 'Authorization', 'Content-Type', 'Content-Disposition']
            allow_methods: ['GET', 'POST', 'DELETE', 'PUT', 'PATCH']