imports:
    - { resource: "services/services_command.yaml" }
    - { resource: "services/services_repository.yaml" }
    - { resource: "services/services_param_converter.yaml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\Controller\:
        resource: '../src/Application/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Application\EventListener\ExceptionListener:
        arguments:
            - '@jms_serializer'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }